#!/usr/bin/env python3
"""
generate_td_interp_headers.py
====================================
Reads the 7 time-domain integral HDF5 databases and generates C++ source files
that embed the tabulated data directly into the executable, removing the HDF5
runtime dependency.

All 7 tables share identical beta[] and mu[] axes, so those are written once
to td_common_axes.cpp.  Each table's fcn[] is written to its own .cpp file
(one translation unit per table for parallel compilation).

Output directory  :  src/green/td_data/
Generated files   :
  td_database.hpp        — dimensions, extern declarations, factory functions
  td_common_axes.cpp     — shared beta[N_BETA] and mu[N_MU]
  td_Gt_fcn.cpp
  td_Gtt_fcn.cpp
  td_Gttt_fcn.cpp
  td_Gtx_fcn.cpp
  td_Gttx_fcn.cpp
  td_Gtxx_fcn.cpp
  td_Gttxx_fcn.cpp

Usage (from project root):
  python aux_tools/generate_td_interp_headers.py

After generation, add the .cpp files to the CMake target (see printed
instructions at the end of the run).
"""

import os
import sys
import numpy as np

try:
    import h5py
except ImportError:
    sys.exit( "ERROR: h5py is required.  Install via: pip install h5py" )

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR   = os.path.dirname( os.path.abspath( __file__ ) )
PROJECT_ROOT = os.path.dirname( SCRIPT_DIR )
DB_DIR       = os.path.join( PROJECT_ROOT, "aux_data",
                              "0_integrals_database", "1_time_domain" )
OUT_DIR      = os.path.join( PROJECT_ROOT, "src", "green", "td_data" )

TABLES = ["Gt", "Gtt", "Gttt", "Gtx", "Gttx", "Gtxx", "Gttxx"]

LICENSE = """\
/*
 * Copyright (c) 2025 Sergio Fernández Ruano / IHCantabria
 *
 * This file is part of SeaMotions Software.
 *
 * SeaMotions is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SeaMotions is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
// Auto-generated by aux_tools/generate_td_interp_headers.py — do not edit.
"""

# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

COLS = 6    # hex-float literals per source line (~132 chars per line)

def array_body( arr ):
    """Return lines of C++ hex-float literals for a flat numpy float64 array.

    Uses Python's float.hex() which produces valid C++17 hex float literals
    (e.g. '0x1.3ae147ae147aep+0') with exact binary round-trip.
    """
    n     = len( arr )
    lines = []
    for i in range( 0, n, COLS ):
        chunk = arr[i : i + COLS]
        parts = [ float(v).hex() for v in chunk ]
        line  = "    " + ", ".join( parts )
        if i + COLS < n:
            line += ","
        lines.append( line )
    return "\n".join( lines )


# ---------------------------------------------------------------------------
# Load all HDF5 tables
# ---------------------------------------------------------------------------

def load_tables():
    """Return (beta, mu, fcn_dict) where fcn_dict[name] is a flat float64 array."""
    beta0 = mu0 = None
    fcn_data = {}
    for name in TABLES:
        path = os.path.join( DB_DIR, name + ".h5" )
        if not os.path.exists( path ):
            sys.exit( f"ERROR: cannot find {path}" )
        with h5py.File( path, "r" ) as f:
            beta = np.array( f["beta"], dtype=np.float64 )
            mu   = np.array( f["mu"],   dtype=np.float64 )
            fcn  = np.array( f["fcn"],  dtype=np.float64 )   # shape (n_beta, n_mu)

        if beta0 is None:
            beta0, mu0 = beta, mu
        else:
            if not np.array_equal( beta, beta0 ):
                sys.exit( f"ERROR: beta axis differs in {name}" )
            if not np.array_equal( mu, mu0 ):
                sys.exit( f"ERROR: mu axis differs in {name}" )

        fcn_data[name] = fcn.ravel( order="C" )   # row-major: [i*n_mu + j]
        print( f"  Loaded {name}: {len(beta):4d} x {len(mu):3d} = {len(fcn_data[name]):,} doubles" )

    return beta0, mu0, fcn_data


# ---------------------------------------------------------------------------
# Write td_database.hpp
# ---------------------------------------------------------------------------

def write_header( n_beta, n_mu ):
    size = n_beta * n_mu

    extern_fcn = "\n".join(
        f"    extern const double {name.lower()}_fcn[{size}];"
        for name in TABLES
    )

    make_ncs = "\n\n".join(
        f"""\
    inline NaturalCubicSpline2D<double> make_ncs_{name}()
    {{
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, {name.lower()}_fcn );
    }}"""
        for name in TABLES
    )

    make_bilin = "\n\n".join(
        f"""\
    inline Bilinear2D<double> make_bilinear_{name}()
    {{
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, {name.lower()}_fcn );
    }}"""
        for name in TABLES
    )

    make_catrom = "\n\n".join(
        f"""\
    inline BicubicCatmullRom2D<double> make_catmullrom_{name}()
    {{
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, {name.lower()}_fcn );
    }}"""
        for name in TABLES
    )

    text = f"""\
{LICENSE}
#pragma once

// ---------------------------------------------------------------------------
// td_database.hpp
//
// Provides embedded access to the 7 time-domain integral tables:
//   Gt, Gtt, Gttt, Gtx, Gttx, Gtxx, Gttxx
//
// All tables share the same beta[] and mu[] axes.
//
// Quick start
// -----------
//   #include "src/green/td_data/td_database.hpp"
//
//   // Construct once (NCS runs the Thomas-algorithm solver — negligible cost)
//   auto ncs_Gt = td_db::make_ncs_Gt();
//
//   // Evaluate many times
//   double val = ncs_Gt.eval( beta, std::log10(mu) );
//
// The make_ncs_*(), make_bilinear_*(), and make_catmullrom_*() functions
// construct independent interpolator objects from the embedded constant arrays.
// Store them as member variables or static locals if you need repeated access.
// ---------------------------------------------------------------------------

#include "../../math/data_fit/interp2d.hpp"

namespace td_db {{

// ---------------------------------------------------------------------------
// Grid dimensions (all 7 tables share the same beta and mu axes)
// ---------------------------------------------------------------------------
static constexpr int N_BETA = {n_beta};   // beta: 0 .. {float(n_beta-1)*0.01:.2f} (step 0.01)
static constexpr int N_MU   = {n_mu};    // mu  : 1e-4 .. 0.9999 (log-spaced)

// Shared axes (defined in td_common_axes.cpp)
extern const double beta[{n_beta}];   // linear beta values
extern const double mu[{n_mu}];       // linear mu values (pass to constructor; NCS stores log10 internally)

// Function value arrays, row-major: fcn[i*N_MU + j] = f(beta[i], mu[j])
// (defined in td_Gt_fcn.cpp .. td_Gttxx_fcn.cpp)
{extern_fcn}

// ---------------------------------------------------------------------------
// NaturalCubicSpline2D factory functions — recommended for production
//   C2 in log(mu), C1 in beta; best accuracy among the three methods
// ---------------------------------------------------------------------------
{make_ncs}

// ---------------------------------------------------------------------------
// BicubicCatmullRom2D factory functions — no precomputation, C1 everywhere
// ---------------------------------------------------------------------------
{make_catrom}

// ---------------------------------------------------------------------------
// Bilinear2D factory functions — lightest weight, C0
// ---------------------------------------------------------------------------
{make_bilin}

}} // namespace td_db
"""
    path = os.path.join( OUT_DIR, "td_database.hpp" )
    with open( path, "w", encoding="utf-8" ) as f:
        f.write( text )
    print( f"  -> {os.path.relpath( path, PROJECT_ROOT )}" )


# ---------------------------------------------------------------------------
# Write td_common_axes.cpp
# ---------------------------------------------------------------------------

def write_axes_cpp( beta, mu ):
    n_beta, n_mu = len(beta), len(mu)
    text  = LICENSE + "\n"
    text += '#include "td_database.hpp"\n\n'
    text += "namespace td_db {\n\n"
    text += f"const double beta[{n_beta}] = {{\n"
    text += array_body( beta ) + "\n"
    text += "};\n\n"
    text += f"const double mu[{n_mu}] = {{\n"
    text += array_body( mu ) + "\n"
    text += "};\n\n"
    text += "} // namespace td_db\n"

    path = os.path.join( OUT_DIR, "td_common_axes.cpp" )
    with open( path, "w", encoding="utf-8" ) as f:
        f.write( text )
    print( f"  -> {os.path.relpath( path, PROJECT_ROOT )}" )


# ---------------------------------------------------------------------------
# Write td_<Name>_fcn.cpp
# ---------------------------------------------------------------------------

def write_fcn_cpp( name, flat_fcn ):
    n       = len( flat_fcn )
    varname = name.lower() + "_fcn"

    text  = LICENSE + "\n"
    text += '#include "td_database.hpp"\n\n'
    text += "namespace td_db {\n\n"
    text += f"const double {varname}[{n}] = {{\n"
    text += array_body( flat_fcn ) + "\n"
    text += "};\n\n"
    text += "} // namespace td_db\n"

    path = os.path.join( OUT_DIR, f"td_{name}_fcn.cpp" )
    with open( path, "w", encoding="utf-8" ) as f:
        f.write( text )
    print( f"  -> {os.path.relpath( path, PROJECT_ROOT )}" )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    os.makedirs( OUT_DIR, exist_ok=True )

    print( f"Database directory : {DB_DIR}" )
    print( f"Output directory   : {OUT_DIR}\n" )

    print( "Loading HDF5 tables:" )
    beta, mu, fcn_data = load_tables()
    n_beta, n_mu = len(beta), len(mu)
    size = n_beta * n_mu
    src_mb = size * 23 / 1024 / 1024   # rough estimate: 23 chars per hex float
    print(
        f"\nGrid  : {n_beta} x {n_mu} = {size:,} doubles per table\n"
        f"Source: ~{src_mb:.0f} MB per fcn file  "
        f"(hex-float literals, exact round-trip)\n"
    )

    print( "Generating files:" )
    write_header( n_beta, n_mu )
    write_axes_cpp( beta, mu )
    for name in TABLES:
        write_fcn_cpp( name, fcn_data[name] )

    cpp_files = ["td_common_axes.cpp"] + [f"td_{n}_fcn.cpp" for n in TABLES]

    print( "\n" + "="*68 )
    print( "Done.  Add the generated .cpp files to your CMake target." )
    print( "="*68 )
    print( """
In the relevant CMakeLists.txt, add:

  set( td_data_dir "${CMAKE_SOURCE_DIR}/src/green/td_data" )
  target_sources( <your_target> PRIVATE""" )
    for f in cpp_files:
        print( f"      ${{td_data_dir}}/{f}" )
    print( "  )" )
    print( """
Then include the header where you evaluate the integrals:

  #include "src/green/td_data/td_database.hpp"

  // Construct once (e.g. as a class member or static local):
  NaturalCubicSpline2D<double> m_ncs_Gt = td_db::make_ncs_Gt();

  // Evaluate:
  double val = m_ncs_Gt.eval( beta, std::log10(mu) );

NOTE: Construction runs the NCS Thomas-algorithm tridiagonal solver
(6000 rows x 100 knots) — takes a few milliseconds total per table.
Store the object; do not reconstruct it on every call.
""" )


if __name__ == "__main__":
    main()
