/*
 * Copyright (c) 2025 Sergio Fernández Ruano / IHCantabria
 *
 * This file is part of SeaMotions Software.
 *
 * SeaMotions is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SeaMotions is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
// Auto-generated by aux_tools/generate_td_interp_headers.py — do not edit.

#pragma once

// ---------------------------------------------------------------------------
// td_database.hpp
//
// Provides embedded access to the 7 time-domain integral tables:
//   Gt, Gtt, Gttt, Gtx, Gttx, Gtxx, Gttxx
//
// All tables share the same beta[] and mu[] axes.
//
// Quick start
// -----------
//   #include "src/green/td_data/td_database.hpp"
//
//   // Construct once (NCS runs the Thomas-algorithm solver — negligible cost)
//   auto ncs_Gt = td_db::make_ncs_Gt();
//
//   // Evaluate many times
//   double val = ncs_Gt.eval( beta, std::log10(mu) );
//
// The make_ncs_*(), make_bilinear_*(), and make_catmullrom_*() functions
// construct independent interpolator objects from the embedded constant arrays.
// Store them as member variables or static locals if you need repeated access.
// ---------------------------------------------------------------------------

#include "../../math/data_fit/interp2d.hpp"

namespace td_db {

// ---------------------------------------------------------------------------
// Grid dimensions (all 7 tables share the same beta and mu axes)
// ---------------------------------------------------------------------------
static constexpr int N_BETA = 6000;   // beta: 0 .. 59.99 (step 0.01)
static constexpr int N_MU   = 100;    // mu  : 1e-4 .. 0.9999 (log-spaced)

// Shared axes (defined in td_common_axes.cpp)
extern const double beta[6000];   // linear beta values
extern const double mu[100];       // linear mu values (pass to constructor; NCS stores log10 internally)

// Function value arrays, row-major: fcn[i*N_MU + j] = f(beta[i], mu[j])
// (defined in td_Gt_fcn.cpp .. td_Gttxx_fcn.cpp)
    extern const double gt_fcn[600000];
    extern const double gtt_fcn[600000];
    extern const double gttt_fcn[600000];
    extern const double gtx_fcn[600000];
    extern const double gttx_fcn[600000];
    extern const double gtxx_fcn[600000];
    extern const double gttxx_fcn[600000];

// ---------------------------------------------------------------------------
// NaturalCubicSpline2D factory functions — recommended for production
//   C2 in log(mu), C1 in beta; best accuracy among the three methods
// ---------------------------------------------------------------------------
    inline NaturalCubicSpline2D<double> make_ncs_Gt()
    {
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, gt_fcn );
    }

    inline NaturalCubicSpline2D<double> make_ncs_Gtt()
    {
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, gtt_fcn );
    }

    inline NaturalCubicSpline2D<double> make_ncs_Gttt()
    {
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, gttt_fcn );
    }

    inline NaturalCubicSpline2D<double> make_ncs_Gtx()
    {
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, gtx_fcn );
    }

    inline NaturalCubicSpline2D<double> make_ncs_Gttx()
    {
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, gttx_fcn );
    }

    inline NaturalCubicSpline2D<double> make_ncs_Gtxx()
    {
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, gtxx_fcn );
    }

    inline NaturalCubicSpline2D<double> make_ncs_Gttxx()
    {
        return NaturalCubicSpline2D<double>( N_BETA, beta, N_MU, mu, gttxx_fcn );
    }

// ---------------------------------------------------------------------------
// BicubicCatmullRom2D factory functions — no precomputation, C1 everywhere
// ---------------------------------------------------------------------------
    inline BicubicCatmullRom2D<double> make_catmullrom_Gt()
    {
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, gt_fcn );
    }

    inline BicubicCatmullRom2D<double> make_catmullrom_Gtt()
    {
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, gtt_fcn );
    }

    inline BicubicCatmullRom2D<double> make_catmullrom_Gttt()
    {
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, gttt_fcn );
    }

    inline BicubicCatmullRom2D<double> make_catmullrom_Gtx()
    {
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, gtx_fcn );
    }

    inline BicubicCatmullRom2D<double> make_catmullrom_Gttx()
    {
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, gttx_fcn );
    }

    inline BicubicCatmullRom2D<double> make_catmullrom_Gtxx()
    {
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, gtxx_fcn );
    }

    inline BicubicCatmullRom2D<double> make_catmullrom_Gttxx()
    {
        return BicubicCatmullRom2D<double>( N_BETA, beta, N_MU, mu, gttxx_fcn );
    }

// ---------------------------------------------------------------------------
// Bilinear2D factory functions — lightest weight, C0
// ---------------------------------------------------------------------------
    inline Bilinear2D<double> make_bilinear_Gt()
    {
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, gt_fcn );
    }

    inline Bilinear2D<double> make_bilinear_Gtt()
    {
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, gtt_fcn );
    }

    inline Bilinear2D<double> make_bilinear_Gttt()
    {
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, gttt_fcn );
    }

    inline Bilinear2D<double> make_bilinear_Gtx()
    {
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, gtx_fcn );
    }

    inline Bilinear2D<double> make_bilinear_Gttx()
    {
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, gttx_fcn );
    }

    inline Bilinear2D<double> make_bilinear_Gtxx()
    {
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, gtxx_fcn );
    }

    inline Bilinear2D<double> make_bilinear_Gttxx()
    {
        return Bilinear2D<double>( N_BETA, beta, N_MU, mu, gttxx_fcn );
    }

} // namespace td_db
