#pragma once

// Auto-generated. Do not edit.

#include "./fin_depth_coeffs/high/L0.hpp"
#include "./fin_depth_coeffs/high/L0_dA.hpp"
#include "./fin_depth_coeffs/high/L0_dB.hpp"
#include "./fin_depth_coeffs/high/L1.hpp"
#include "./fin_depth_coeffs/high/L1_dA.hpp"
#include "./fin_depth_coeffs/high/L1_dB.hpp"
#include "./fin_depth_coeffs/high/L2.hpp"
#include "./fin_depth_coeffs/high/L3.hpp"
#include "./fin_depth_coeffs/high/L3_dA.hpp"
#include "./fin_depth_coeffs/high/L3_dB.hpp"
#include "./fin_depth_coeffs/high/Linf.hpp"
#include "./fin_depth_coeffs/high/Linf_dA.hpp"
#include "./fin_depth_coeffs/high/Linf_dB.hpp"
#include "./fin_depth_coeffs/high/M1.hpp"
#include "./fin_depth_coeffs/high/M1_dA.hpp"
#include "./fin_depth_coeffs/high/M1_dB.hpp"
#include "./fin_depth_coeffs/high/M2.hpp"
#include "./fin_depth_coeffs/high/M3.hpp"
#include "./fin_depth_coeffs/high/M3_dA.hpp"
#include "./fin_depth_coeffs/high/M3_dB.hpp"
#include "./inf_depth_coeffs/high/R00_dX.hpp"
#include "./inf_depth_coeffs/high/R11.hpp"
#include "./inf_depth_coeffs/high/R11_dX.hpp"
