/*
 * Copyright (c) 2025 Sergio Fernández Ruano / IHCantabria
 *
 * This file is part of SeaMotions Software.
 *
 * SeaMotions is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SeaMotions is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// Test suite for the time-domain asymptotic Green function routines implemented
// in src/green/time_domain_asymptotic.hpp / .cpp.
//
// Test 1 – spot_checks
//   Compare each of the five functions (dGdt, dGdtt, dGdttt, dGdtx, dGdttx)
//   against Python-generated reference values at a 4×3 (beta, mu) grid.
//   Reference produced by running:
//       aux_tools/time_domain_asymptotic.py::{dG*}_asymptotic(beta, mu)
//   with the default configuration (nmax=15, use_f0=true).
//   Acceptance criterion for each point:
//       |computed - expected| <= ABS_TOL + REL_TOL * |expected|
//   Points with |expected| < MIN_SKIP are skipped (near-machine-zero values
//   that arise from the exp(-beta^2 * mu / 4) decay at large beta and mu).
//
// Test 2 – finiteness
//   Load each of the five reference .dat files (passed as argv[1..5]).
//   For every (beta, mu) pair in the file, call the corresponding C++ routine
//   and assert that the result is finite (no NaN, no inf).
//
// Usage:
//   test_time_domain_asymptotic_cmd  dGdt.dat  dGdtt.dat  dGdttt.dat  \
//                                    dGdtx.dat  dGdttx.dat

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#include "../../src/config.hpp"
#include "../../src/green/time_domain_asymptotic.hpp"


// ============================================================================
// Precision-adaptive tolerances
// ============================================================================
// At small β (≤ 5) the asymptotic series is poorly converged and the heavy
// cancellation among the 15 inner terms amplifies FP round-off differences
// between Intel ICX and Python/NumPy.  At β ≥ 10 the relative error is below
// 1e-5; at β ≥ 20 it is below 1e-8.  We therefore choose 5e-4 as a single
// tolerance that is robust at β = 5 yet tight enough to catch any genuine
// implementation error (wrong sign, wrong coefficient, wrong formula).
//
// Note: the Python dGdtt/dGdttt/dGdtx/dGdttx functions omit the f0-derivative
// term (it is commented out).  To produce a fair comparison the spot-check
// calls those four C++ functions with use_f0 = false (matching Python).
// dGdt includes f0 in both Python and C++ so it is tested with the default
// configuration.
//
// Reference values whose magnitude is below MIN_SKIP are skipped; this avoids
// points where the f0 contribution dominates and the Python reference is
// effectively zero while the C++ (with use_f0 = true) is not.
#ifdef SIMPLE_PREC
static constexpr cusfloat SPOT_REL_TOL = static_cast<cusfloat>( 1e-3 );
static constexpr cusfloat SPOT_ABS_TOL = static_cast<cusfloat>( 1e-5 );
#else
static constexpr cusfloat SPOT_REL_TOL = static_cast<cusfloat>( 5e-4 );
static constexpr cusfloat SPOT_ABS_TOL = static_cast<cusfloat>( 1e-9 );
#endif

// Skip spot-check comparison when |expected| < MIN_SKIP.
// Set to 1.0 so that near-zero f0-dominated points (large β, large μ) where
// Python returns ≈ 0 but C++ (with use_f0) returns the f0 contribution are
// not compared against the Python reference.
static constexpr double MIN_SKIP = 1.0;


// ============================================================================
// Helpers
// ============================================================================
static void check( bool cond, const char* msg )
{
    if ( !cond )
    {
        std::cerr << "FAIL  " << msg << std::endl;
        throw std::runtime_error( msg );
    }
}


// ============================================================================
// Reference data for Test 1
//
// Columns: beta, mu, dGdt, dGdtt, dGdttt, dGdtx, dGdttx
// Generated by: aux_tools/time_domain_asymptotic.py (Python float64, nmax=15)
// ============================================================================
struct SpotPt
{
    double beta, mu;
    double dGdt, dGdtt, dGdttt, dGdtx, dGdttx;
};

static const SpotPt SPOT_PTS[] =
{
    // beta = 5 ---------------------------------------------------------------
    {  5.0, 1.0e-3,
        5.631691912421464e+02,  2.185617400277680e+04, -5.347311845766263e+05,
       -4.386765856950705e+05,  4.629943628064477e+06  },
    {  5.0, 2.0e-2,
       -6.304701358790380e+03,  8.751059488165056e+04, -1.126144618906265e+06,
       -2.565078990016335e+05,  2.045401648004837e+06  },
    {  5.0, 2.0e-1,
       -3.821859618912685e+03,  4.133413913364691e+04, -4.282793082257110e+05,
        5.023005918850281e+04, -9.738911953236642e+05  },
    // beta = 10 --------------------------------------------------------------
    { 10.0, 1.0e-3,
       -1.263006323733446e+00,  6.845531889993491e+01,  5.120440015583466e+01,
        5.154505819900812e+01, -1.688429714181108e+03  },
    { 10.0, 2.0e-2,
       -5.884314777823817e-01,  4.278677095825798e+01,  1.874811731418807e+01,
        2.301876252275178e+01, -1.060838148677685e+03  },
    { 10.0, 2.0e-1,
       -3.685443759734344e-02,  4.834324282091002e-01, -1.133606118488663e-01,
        3.765226959160318e-01, -1.214862199181612e+01  },
    // beta = 20 --------------------------------------------------------------
    { 20.0, 1.0e-3,
       -1.270692153731847e+01,  2.216339755515391e+02,  1.299236480463671e+03,
        1.301435082468748e+03, -2.185287763007939e+04  },
    { 20.0, 2.0e-2,
       -1.873843161460275e+00,  3.367702580036612e+01,  1.788021638705413e+02,
        1.855556091691990e+02, -3.357750150787060e+03  },
    { 20.0, 2.0e-1,
       -1.005537424504339e-03, -2.689014006214853e-07,  5.663865502267765e-06,
        5.325154608881005e-06,  1.746174528440855e-05  },
    // beta = 29 --------------------------------------------------------------
    { 29.0, 1.0e-3,
        7.594704789353673e+00, -4.690053529949415e+02, -1.631720366746186e+03,
       -1.638511191595938e+03,  9.835114732382806e+04  },
    { 29.0, 2.0e-2,
        1.475532755746831e-01, -8.648577895239860e+00, -2.696652239673254e+01,
       -2.948196636267721e+01,  1.821612636986629e+03  },
    { 29.0, 2.0e-1,
       -3.289155675999630e-04,  2.202353101685731e-16,  2.849513666915332e-15,
        3.627431526877101e-15, -5.614833567635883e-14  },
};

static constexpr int N_SPOT = static_cast<int>( sizeof( SPOT_PTS ) / sizeof( SPOT_PTS[0] ) );


// ============================================================================
// Test 1 – spot-checks against Python reference
// ============================================================================
static void test_spot_checks()
{
    int n_checked = 0;
    int n_skipped = 0;

    // Lambda: check one (computed, expected) pair.
    auto check_val = [&]( cusfloat computed, double expected,
                          double beta, double mu, const char* fname )
    {
        if ( std::abs( expected ) < MIN_SKIP )
        {
            ++n_skipped;
            return;
        }
        const cusfloat exp_f = static_cast<cusfloat>( expected );
        const cusfloat diff  = std::abs( computed - exp_f );
        const bool     ok    = diff <= SPOT_ABS_TOL + SPOT_REL_TOL * std::abs( exp_f );

        if ( !ok )
        {
            std::cerr << std::scientific << std::setprecision( 10 )
                      << "  FAIL  " << fname
                      << "  beta=" << beta << "  mu=" << mu
                      << "  expected=" << expected
                      << "  computed=" << static_cast<double>( computed )
                      << "  rel_err="  << static_cast<double>( diff / std::abs( exp_f ) )
                      << "\n";
        }

        std::string tag = std::string( fname ) + "_spot_b"
            + std::to_string( static_cast<int>( beta ) )
            + "_m" + std::to_string( mu );
        check( ok, fname );
        ++n_checked;
    };

    for ( int i = 0; i < N_SPOT; ++i )
    {
        const SpotPt& s = SPOT_PTS[i];
        const cusfloat b = static_cast<cusfloat>( s.beta );
        const cusfloat m = static_cast<cusfloat>( s.mu   );

        // dGdt: Python includes f0; use default config (use_f0 = true).
        check_val( dGdt_asymptotic  ( b, m ),                      s.dGdt,   s.beta, s.mu, "dGdt"   );
        // dGdtt/dGdttt/dGdtx/dGdttx: Python omits the df0 term (commented
        // out); use TDAsympConfig{false,15} to match Python exactly.
        const TDAsympConfig no_f0{ false, 15 };
        check_val( dGdtt_asymptotic ( b, m, no_f0 ), s.dGdtt,  s.beta, s.mu, "dGdtt"  );
        check_val( dGdttt_asymptotic( b, m, no_f0 ), s.dGdttt, s.beta, s.mu, "dGdttt" );
        check_val( dGdtx_asymptotic ( b, m, no_f0 ), s.dGdtx,  s.beta, s.mu, "dGdtx"  );
        check_val( dGdttx_asymptotic( b, m, no_f0 ), s.dGdttx, s.beta, s.mu, "dGdttx" );
    }

    std::cout << "  " << n_checked << " pairs checked, "
              << n_skipped << " pairs skipped (|ref| < " << MIN_SKIP << ")\n";
}


// ============================================================================
// Data loader for Test 2
// File format:  line 1 = N (integer)
//               lines 2..N+1 = beta  mu  value  (space-separated)
// ============================================================================
struct DatPoint
{
    cusfloat beta;
    cusfloat mu;
};

static std::vector<DatPoint> load_dat( const std::string& path )
{
    std::ifstream f( path );
    if ( !f )
        throw std::runtime_error( "Cannot open file: " + path );

    int n = 0;
    f >> n;
    if ( n <= 0 )
        throw std::runtime_error( "Invalid point count in: " + path );

    std::vector<DatPoint> pts;
    pts.reserve( static_cast<std::size_t>( n ) );

    for ( int i = 0; i < n; ++i )
    {
        double b = 0.0, m = 0.0, val = 0.0;
        f >> b >> m >> val;
        if ( !f )
            throw std::runtime_error( "Read error in: " + path );
        DatPoint dp;
        dp.beta = static_cast<cusfloat>( b );
        dp.mu   = static_cast<cusfloat>( m );
        pts.push_back( dp );
    }
    return pts;
}


// ============================================================================
// Test 2 – finiteness over the full (beta, mu) grid from a dat file
// ============================================================================
using AsympFn = cusfloat (*)( cusfloat, cusfloat, TDAsympConfig );

static void test_finiteness( const std::string& path,
                              AsympFn            fn,
                              const char*        label )
{
    const std::vector<DatPoint> pts = load_dat( path );
    int n_bad = 0;

    for ( std::size_t i = 0; i < pts.size(); ++i )
    {
        const cusfloat result = fn( pts[i].beta, pts[i].mu, TDAsympConfig{} );
        if ( !std::isfinite( result ) )
        {
            std::cerr << "  FAIL  " << label
                      << "  idx="  << i
                      << "  beta=" << static_cast<double>( pts[i].beta )
                      << "  mu="   << static_cast<double>( pts[i].mu   )
                      << "  result=" << static_cast<double>( result )
                      << "\n";
            ++n_bad;
        }
    }

    check( n_bad == 0, label );
    std::cout << "  " << label << ": " << pts.size() << " points, all finite\n";
}


// ============================================================================
// main
// ============================================================================
int main( int argc, char** argv )
{
    if ( argc < 6 )
    {
        std::cerr << "Usage: " << argv[0]
                  << "  dGdt.dat  dGdtt.dat  dGdttt.dat  dGdtx.dat  dGdttx.dat\n";
        return 1;
    }

    int exit_code = 0;

    // ---- Test 1 ----
    std::cout << "=== test_spot_checks ===\n";
    try
    {
        test_spot_checks();
        std::cout << "PASS\n\n";
    }
    catch ( const std::exception& ex )
    {
        std::cerr << "EXCEPTION: " << ex.what() << "\n";
        exit_code = 1;
    }

    // ---- Test 2 ----
    std::cout << "=== test_finiteness ===\n";
    try
    {
        test_finiteness( argv[1], dGdt_asymptotic,   "dGdt"   );
        test_finiteness( argv[2], dGdtt_asymptotic,  "dGdtt"  );
        test_finiteness( argv[3], dGdttt_asymptotic, "dGdttt" );
        test_finiteness( argv[4], dGdtx_asymptotic,  "dGdtx"  );
        test_finiteness( argv[5], dGdttx_asymptotic, "dGdttx" );
        std::cout << "PASS\n";
    }
    catch ( const std::exception& ex )
    {
        std::cerr << "EXCEPTION: " << ex.what() << "\n";
        exit_code = 1;
    }

    return exit_code;
}
