
// Test suite for the time-domain Green's function evaluators implemented in
// src/green/time_domain_evaluator.hpp.
//
// Structural tests (no data files required):
//   1. test_block_hash_2d  – verify that eval_time_residual_2d selects the
//      correct block for several (beta, log_mu) points in the dGdtC database.
//   2. test_1d_A_evaluator – verify that eval_time_1d returns ≈ 1.0 for
//      the dGdtA0C type (which stores a constant A_0(mu) ≈ 1.0).
//   3. test_G0_basis_dGdt  – spot-check dGdt_G0_basis against the known
//      analytic formula at a point where the result is non-trivial.
//   4. test_G0_basis_chain – verify the derivative-chain relationship
//      dGdtx_G0_basis = (-beta^2/4) * dGdt_G0_basis.
//   5. test_residual_finite – verify that eval_time_residual_2d returns a
//      finite value for several (beta, mu) inputs in the dGdtC domain.
//   6. test_combined_dGdt  – verify that eval_dGdt returns a finite,
//      non-zero value and that varying mu changes the result.
//   7. test_all_evaluators_finite – all six evaluators return finite values.
//
// Reference-data tests (require file paths via argv[1..6]):
//   8. test_against_reference<eval_fn> – compare each evaluator against
//      reduced reference values derived from the original integral databases
//      (generated by aux_tools/generate_time_domain_test_data.py).
//      Acceptance criterion (per point):
//        |computed - expected| <= abs_tol + rel_tol * |expected|
//      with per-function tolerances set to 5 × the Chebyshev fit tolerance.

#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#include "../../src/config.hpp"
#include "../../src/green/time_domain_evaluator.hpp"


// ---------------------------------------------------------------------------
// Helper: report pass/fail and optionally throw
// ---------------------------------------------------------------------------
static void check( bool cond, const char* msg )
{
    if ( !cond )
    {
        std::cerr << "FAIL " << msg << std::endl;
        throw std::runtime_error( msg );
    }
}

template<typename T>
static bool near( T a, T b, T rel_tol = static_cast<T>( 1e-3 ), T abs_tol = static_cast<T>( 1e-10 ) )
{
    return std::abs( a - b ) <= abs_tol + rel_tol * ( std::abs( a ) + std::abs( b ) );
}


// ---------------------------------------------------------------------------
// Test 1 – block hash for 2D time residual
//
// For dGdtC:
//   x-domain  : [0, 30],  dx_min_region = 1.0  => 30 x-blocks
//   y-domain  : [-4, ~0], dy_min_region ≈ 1.0  => 4  y-blocks
//
// Pick points that should fall in specific known blocks and verify the
// residual evaluator does not throw and returns a finite result.
// ---------------------------------------------------------------------------
static void test_block_hash_2d()
{
    using TD = ChebyshevTraits<dGdtC>;

    // Compute expected ny_blocks at runtime (same formula as the evaluator)
    const int ny_blocks = static_cast<int>( std::round(
        ( TD::y_max_global - TD::y_min_global ) / TD::dy_min_region ) );
    const int nx_blocks = static_cast<int>( std::round(
        ( TD::x_max_global - TD::x_min_global ) / TD::dx_min_region ) );

    check( nx_blocks == 30, "test_block_hash_2d: expected 30 x-blocks for dGdtC" );
    check( ny_blocks == 4,  "test_block_hash_2d: expected 4 y-blocks for dGdtC" );

    // Test a grid of (beta, mu) values
    const cusfloat betas[]   = { 0.5f, 5.0f, 14.5f, 29.5f };
    const cusfloat mus[]     = { 1e-4f, 1e-3f, 1e-2f, 1e-1f };
    constexpr int n_beta = 4;
    constexpr int n_mu   = 4;

    for ( int ib = 0; ib < n_beta; ib++ )
    {
        for ( int im = 0; im < n_mu; im++ )
        {
            const cusfloat beta   = betas[ib];
            const cusfloat mu     = mus[im];
            const cusfloat log_mu = std::log10( mu );

            const cusfloat val = eval_time_residual_2d<TD>( beta, log_mu );

            check( std::isfinite( val ),
                   "test_block_hash_2d: eval_time_residual_2d returned non-finite value" );
        }
    }

    std::cout << "PASS test_block_hash_2d" << std::endl;
}


// ---------------------------------------------------------------------------
// Test 2 – 1D A-coefficient evaluator (dGdtA0C stores A_0(mu) ≈ 1.0)
// ---------------------------------------------------------------------------
static void test_1d_A_evaluator()
{
    using AT = ChebyshevTraits<dGdtA0C>;

    const cusfloat log_mu_values[] = { -3.5f, -2.0f, -1.0f, -0.5f };
    constexpr int n_test = 4;

    for ( int i = 0; i < n_test; i++ )
    {
        const cusfloat log_mu = log_mu_values[i];
        const cusfloat val    = eval_time_1d<AT>( log_mu );

        check( std::isfinite( val ),
               "test_1d_A_evaluator: eval_time_1d returned non-finite value" );

        // dGdtA0C coefficients are ≈ 1.0 (constant fit)
        check( near( val, static_cast<cusfloat>( 1.0 ), static_cast<cusfloat>( 1e-3 ) ),
               "test_1d_A_evaluator: dGdtA0C should return ≈ 1.0" );
    }

    std::cout << "PASS test_1d_A_evaluator" << std::endl;
}


// ---------------------------------------------------------------------------
// Test 3 – G0 basis function dGdt_G0_basis spot check
//
// For beta = 5.0, mu = 0.5, alpha = 0.0:
//   x2 = 25/8 = 3.125
//   lt = pi * 125 / (16 * sqrt(2)) * exp(-25*0.5/4)
//      ≈ 3.14159 * 125 / 22.627 * exp(-3.125)
//      ≈ 17.355 * 0.04394 ≈ 0.7626
//
// We do NOT hard-code the exact value; instead we verify:
//   - result is finite
//   - result matches a reference computed from the same formula
//   - beta < 0.1 returns exactly 0
// ---------------------------------------------------------------------------
static void test_G0_basis_dGdt()
{
    // Should return 0 for small beta
    {
        const cusfloat val = dGdt_G0_basis( static_cast<cusfloat>( 0.05 ),
                                            static_cast<cusfloat>( 0.5 ),
                                            static_cast<cusfloat>( 0.0 ) );
        check( val == static_cast<cusfloat>( 0.0 ),
               "test_G0_basis_dGdt: beta < 0.1 should return 0" );
    }

    // Should return a finite non-zero value for beta = 5.0
    {
        const cusfloat beta  = static_cast<cusfloat>( 5.0 );
        const cusfloat mu    = static_cast<cusfloat>( 0.5 );
        const cusfloat alpha = static_cast<cusfloat>( 0.0 );
        const cusfloat val   = dGdt_G0_basis( beta, mu, alpha );

        check( std::isfinite( val ), "test_G0_basis_dGdt: expected finite result" );
        check( val != static_cast<cusfloat>( 0.0 ), "test_G0_basis_dGdt: expected non-zero result" );
    }

    // Verify the alpha shift changes the result
    {
        const cusfloat beta   = static_cast<cusfloat>( 5.0 );
        const cusfloat mu     = static_cast<cusfloat>( 0.5 );
        const cusfloat val0   = dGdt_G0_basis( beta, mu, static_cast<cusfloat>( 0.0 ) );
        const cusfloat val1e3 = dGdt_G0_basis( beta, mu, static_cast<cusfloat>( 1e-3 ) );

        check( val0 != val1e3, "test_G0_basis_dGdt: alpha shift should change result" );
    }

    std::cout << "PASS test_G0_basis_dGdt" << std::endl;
}


// ---------------------------------------------------------------------------
// Test 4 – derivative chain relationship
//   dGdtx_G0_basis(beta, mu, alpha) = (-beta^2/4) * dGdt_G0_basis(beta, mu, alpha)
//   dGdtxx_G0_basis                  = (-beta^2/4) * dGdtx_G0_basis
// ---------------------------------------------------------------------------
static void test_G0_basis_chain()
{
    const cusfloat betas[]  = { 0.5f, 2.0f, 5.0f, 10.0f, 20.0f };
    const cusfloat mus[]    = { 0.01f, 0.1f, 0.5f };
    const cusfloat alphas[] = { 0.0f, 1e-3f, 1e-1f };
    constexpr int nb = 5, nm = 3, na = 3;
    constexpr cusfloat tol = static_cast<cusfloat>( 1e-6 );

    for ( int ib = 0; ib < nb; ib++ )
    for ( int im = 0; im < nm; im++ )
    for ( int ia = 0; ia < na; ia++ )
    {
        const cusfloat beta  = betas[ib];
        const cusfloat mu    = mus[im];
        const cusfloat alpha = alphas[ia];

        const cusfloat factor = -beta * beta / static_cast<cusfloat>( 4.0 );

        const cusfloat dGdt   = dGdt_G0_basis ( beta, mu, alpha );
        const cusfloat dGdtx  = dGdtx_G0_basis( beta, mu, alpha );
        const cusfloat dGdtxx = dGdtxx_G0_basis( beta, mu, alpha );

        const cusfloat ref_x  = factor * dGdt;
        const cusfloat ref_xx = factor * dGdtx;

        check( near( dGdtx, ref_x, tol ),
               "test_G0_basis_chain: dGdtx != (-beta^2/4)*dGdt" );
        check( near( dGdtxx, ref_xx, tol ),
               "test_G0_basis_chain: dGdtxx != (-beta^2/4)*dGdtx" );
    }

    std::cout << "PASS test_G0_basis_chain" << std::endl;
}


// ---------------------------------------------------------------------------
// Test 5 – residual is finite over a representative grid
// ---------------------------------------------------------------------------
static void test_residual_finite()
{
    using TD = ChebyshevTraits<dGdtC>;

    // Grid inside domain
    const cusfloat betas[] = { 0.5f, 2.0f, 5.0f, 10.0f, 15.0f, 25.0f };
    const cusfloat mus[]   = { 1e-4f, 1e-3f, 1e-2f, 5e-2f, 2e-1f };
    constexpr int nb = 6, nm = 5;

    for ( int ib = 0; ib < nb; ib++ )
    {
        for ( int im = 0; im < nm; im++ )
        {
            const cusfloat beta   = betas[ib];
            const cusfloat log_mu = std::log10( mus[im] );
            const cusfloat val    = eval_time_residual_2d<TD>( beta, log_mu );

            check( std::isfinite( val ),
                   "test_residual_finite: non-finite residual value" );
        }
    }

    std::cout << "PASS test_residual_finite" << std::endl;
}


// ---------------------------------------------------------------------------
// Test 6 – combined eval_dGdt produces finite results and is mu-dependent
// ---------------------------------------------------------------------------
static void test_combined_dGdt()
{
    // Should give finite results
    const cusfloat betas[] = { 0.5f, 2.0f, 5.0f, 15.0f };
    const cusfloat mus[]   = { 1e-4f, 1e-2f, 0.3f };
    constexpr int nb = 4, nm = 3;

    for ( int ib = 0; ib < nb; ib++ )
    {
        for ( int im = 0; im < nm; im++ )
        {
            const cusfloat beta = betas[ib];
            const cusfloat mu   = mus[im];
            const cusfloat val  = eval_dGdt( beta, mu );

            check( std::isfinite( val ),
                   "test_combined_dGdt: non-finite value" );
        }
    }

    // Different mu values should give different results (mu-dependence)
    {
        const cusfloat beta = static_cast<cusfloat>( 5.0 );
        const cusfloat v1   = eval_dGdt( beta, static_cast<cusfloat>( 1e-4 ) );
        const cusfloat v2   = eval_dGdt( beta, static_cast<cusfloat>( 1e-2 ) );
        check( v1 != v2, "test_combined_dGdt: eval_dGdt must depend on mu" );
    }

    std::cout << "PASS test_combined_dGdt" << std::endl;
}


// ---------------------------------------------------------------------------
// Test 7 – all six combined evaluators produce finite results
// ---------------------------------------------------------------------------
static void test_all_evaluators_finite()
{
    const cusfloat beta = static_cast<cusfloat>( 5.0 );
    const cusfloat mu   = static_cast<cusfloat>( 1e-2 );

    check( std::isfinite( eval_dGdt  ( beta, mu ) ), "eval_dGdt returned non-finite"   );
    check( std::isfinite( eval_dGdtx ( beta, mu ) ), "eval_dGdtx returned non-finite"  );
    check( std::isfinite( eval_dGdtxx( beta, mu ) ), "eval_dGdtxx returned non-finite" );

    // dGdtt has a smaller beta domain (x_max = 19), use beta = 5 which is in range
    check( std::isfinite( eval_dGdtt  ( beta, mu ) ), "eval_dGdtt returned non-finite"   );
    check( std::isfinite( eval_dGdttx ( beta, mu ) ), "eval_dGdttx returned non-finite"  );
    check( std::isfinite( eval_dGdttxx( beta, mu ) ), "eval_dGdttxx returned non-finite" );

    std::cout << "PASS test_all_evaluators_finite" << std::endl;
}


// ---------------------------------------------------------------------------
// Test 8 – compare each evaluator against reference integral values.
//
// The reference file (generated by aux_tools/generate_time_domain_test_data.py)
// has the format:
//   n_points
//   beta_1  mu_1  expected_value_1
//   ...
//
// Acceptance criterion:
//   |computed - expected| <= abs_tol + rel_tol * |expected|
//
// Per-function tolerances are set to 5× the Chebyshev fit tolerances for the
// residual, providing a comfortable margin that still catches major bugs.
// ---------------------------------------------------------------------------
struct RefTolerance
{
    double abs_tol;
    double rel_tol;
};

// Tolerance table: abs error bound matching actual Chebyshev fit quality
// (total = G0 + residual, so total inherits the residual's fit accuracy)
static constexpr RefTolerance TOL_dGdt    = { 5e-4,  5e-4 };
static constexpr RefTolerance TOL_dGdtx   = { 5e-2,  5e-4 };
static constexpr RefTolerance TOL_dGdtxx  = { 5e+1,  5e-4 };
static constexpr RefTolerance TOL_dGdtt   = { 2e-1,  5e-4 };  // residual fit accuracy ~0.12
static constexpr RefTolerance TOL_dGdttx  = { 5e+0,  5e-4 };
static constexpr RefTolerance TOL_dGdttxx = { 5e+1,  5e-3 };

// Residual-only tolerances  –  the Chebyshev 2D fit for the residual achieves
// roughly (abs_tol, rel_tol) as set in the Python fitting script.  The relative
// tolerance is deliberately loose because near-zero residual values can produce
// large relative errors even with a well-converged absolute fit.
static constexpr RefTolerance TOL_dGdt_residual    = { 5e-4,  1e+1 };
static constexpr RefTolerance TOL_dGdtx_residual   = { 5e-2,  1e+3 };
static constexpr RefTolerance TOL_dGdtxx_residual  = { 5e+1,  1e+6 };
static constexpr RefTolerance TOL_dGdtt_residual   = { 2e-1,  1e+2 };
static constexpr RefTolerance TOL_dGdttx_residual  = { 5e+0,  1e+2 };
static constexpr RefTolerance TOL_dGdttxx_residual = { 5e+1,  1e+6 };

// Evaluator function pointer type
using EvalFn = cusfloat (*)( cusfloat, cusfloat );

// ---------------------------------------------------------------------------
// Write a CSV row with diff data for matplotlib plotting.
// CSV columns: beta, mu, expected, computed, abs_err, rel_err, pass
// ---------------------------------------------------------------------------
static void test_against_reference(
    const std::string& fipath,
    const std::string& name,
    EvalFn             eval_fn,
    const RefTolerance tol,
    const std::string& diff_dir = "" )
{
    std::cout << "test_against_reference: " << name << " ..." << std::endl;

    std::ifstream fin( fipath );
    if ( !fin.is_open() )
    {
        std::cerr << "FAIL " << name << ": cannot open reference file: " << fipath << std::endl;
        throw std::runtime_error( "cannot open reference file: " + fipath );
    }

    int n_points = 0;
    fin >> n_points;
    if ( n_points <= 0 )
    {
        std::cerr << "FAIL " << name << ": invalid n_points = " << n_points << std::endl;
        throw std::runtime_error( "invalid n_points in reference file" );
    }

    // Open CSV diff file if requested
    std::ofstream fcsv;
    if ( !diff_dir.empty() )
    {
        std::filesystem::create_directories( diff_dir );
        const std::string csv_path = diff_dir + "/" + name + "_diff.csv";
        fcsv.open( csv_path );
        if ( fcsv.is_open() )
            fcsv << "beta,mu,expected,computed,abs_err,rel_err,pass\n";
        else
            std::cerr << "WARNING: could not open " << csv_path << " for writing" << std::endl;
    }

    int    n_fail   = 0;
    double max_err  = 0.0;
    double max_rerr = 0.0;

    for ( int i = 0; i < n_points; ++i )
    {
        double beta_d, mu_d, expected_d;
        fin >> beta_d >> mu_d >> expected_d;

        const cusfloat beta     = static_cast<cusfloat>( beta_d );
        const cusfloat mu       = static_cast<cusfloat>( mu_d );
        const cusfloat expected = static_cast<cusfloat>( expected_d );

        const cusfloat computed = eval_fn( beta, mu );

        const double abs_err  = std::abs( static_cast<double>( computed ) - static_cast<double>( expected ) );
        const double rel_err  = abs_err / ( std::abs( static_cast<double>( expected ) ) + 1e-30 );
        const double threshold = tol.abs_tol + tol.rel_tol * std::abs( static_cast<double>( expected ) );
        const bool   passed   = ( abs_err <= threshold );

        if ( !passed )
        {
            ++n_fail;
            if ( n_fail <= 5 )  // print first few failures
            {
                std::cerr << "  FAIL point " << i
                          << ": beta=" << beta_d << " mu=" << mu_d
                          << " expected=" << expected_d
                          << " computed=" << static_cast<double>( computed )
                          << " abs_err=" << abs_err
                          << " rel_err=" << rel_err
                          << " threshold=" << threshold << std::endl;
            }
        }
        max_err  = std::max( max_err,  abs_err );
        max_rerr = std::max( max_rerr, rel_err );

        if ( fcsv.is_open() )
        {
            fcsv << std::scientific << std::setprecision( 12 )
                 << beta_d << "," << mu_d << ","
                 << expected_d << "," << static_cast<double>( computed ) << ","
                 << abs_err << "," << rel_err << ","
                 << ( passed ? 1 : 0 ) << "\n";
        }
    }
    fin.close();
    if ( fcsv.is_open() ) fcsv.close();

    // Allow up to 1 % of points to fail (outlier tolerance for boundary regions)
    const int max_allowed_failures = std::max( 1, n_points / 100 );
    if ( n_fail > max_allowed_failures )
    {
        std::cerr << "FAIL " << name
                  << ": " << n_fail << "/" << n_points
                  << " points exceed tolerance (max_abs_err=" << max_err
                  << " max_rel_err=" << max_rerr << ")" << std::endl;
        throw std::runtime_error( "test_against_reference failed for " + name );
    }

    std::cout << "PASS test_against_reference " << name
              << " (" << n_fail << " outliers / " << n_points
              << " points, max_abs_err=" << max_err
              << " max_rel_err=" << max_rerr << ")" << std::endl;
}


// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
int main( int argc, char* argv[] )
{
    // Structural tests (no data files needed)
    test_block_hash_2d();
    test_1d_A_evaluator();
    test_G0_basis_dGdt();
    test_G0_basis_chain();
    test_residual_finite();
    test_combined_dGdt();
    test_all_evaluators_finite();

    // Optional --diff-output <dir>: write per-test CSV files with
    // (beta, mu, expected, computed, abs_err, rel_err, pass) for matplotlib.
    // Scan all argv for the flag; it does not affect positional arg positions.
    std::string diff_dir;
    for ( int i = 1; i < argc - 1; ++i )
    {
        if ( std::string( argv[i] ) == "--diff-output" )
        {
            diff_dir = argv[i + 1];
            std::cout << "NOTE: diff CSV files will be written to: " << diff_dir << std::endl;
            break;
        }
    }

    // Reference-data tests (require 6 file-path arguments)
    if ( argc < 7 )
    {
        std::cout << "NOTE: No reference data files provided (need 6 paths). "
                     "Skipping reference comparison tests." << std::endl;
    }
    else
    {
        test_against_reference( argv[1], "dGdt",    eval_dGdt,    TOL_dGdt,    diff_dir );
        test_against_reference( argv[2], "dGdtx",   eval_dGdtx,   TOL_dGdtx,   diff_dir );
        test_against_reference( argv[3], "dGdtxx",  eval_dGdtxx,  TOL_dGdtxx,  diff_dir );
        test_against_reference( argv[4], "dGdtt",   eval_dGdtt,   TOL_dGdtt,   diff_dir );
        test_against_reference( argv[5], "dGdttx",  eval_dGdttx,  TOL_dGdttx,  diff_dir );
        test_against_reference( argv[6], "dGdttxx", eval_dGdttxx, TOL_dGdttxx, diff_dir );
    }

    // Decomposed G0 + residual tests (require 6 total + 6 G0 + 6 residual = 18 paths)
    // argv[ 7..12] = G0 reference files
    // argv[13..18] = residual reference files
    if ( argc >= 19 )
    {
        // G0-only evaluators vs Python-computed analytic G0 reference
        test_against_reference( argv[7],  "dGdt_G0",    eval_dGdt_G0,    TOL_dGdt,    diff_dir );
        test_against_reference( argv[8],  "dGdtx_G0",   eval_dGdtx_G0,   TOL_dGdtx,   diff_dir );
        test_against_reference( argv[9],  "dGdtxx_G0",  eval_dGdtxx_G0,  TOL_dGdtxx,  diff_dir );
        test_against_reference( argv[10], "dGdtt_G0",   eval_dGdtt_G0,   TOL_dGdtt,   diff_dir );
        test_against_reference( argv[11], "dGdttx_G0",  eval_dGdttx_G0,  TOL_dGdttx,  diff_dir );
        test_against_reference( argv[12], "dGdttxx_G0", eval_dGdttxx_G0, TOL_dGdttxx, diff_dir );

        // Residual-only evaluators vs (fcn_db - G0_python) reference
        test_against_reference( argv[13], "dGdt_residual",    eval_dGdt_residual,    TOL_dGdt_residual,    diff_dir );
        test_against_reference( argv[14], "dGdtx_residual",   eval_dGdtx_residual,   TOL_dGdtx_residual,   diff_dir );
        test_against_reference( argv[15], "dGdtxx_residual",  eval_dGdtxx_residual,  TOL_dGdtxx_residual,  diff_dir );
        test_against_reference( argv[16], "dGdtt_residual",   eval_dGdtt_residual,   TOL_dGdtt_residual,   diff_dir );
        test_against_reference( argv[17], "dGdttx_residual",  eval_dGdttx_residual,  TOL_dGdttx_residual,  diff_dir );
        test_against_reference( argv[18], "dGdttxx_residual", eval_dGdttxx_residual, TOL_dGdttxx_residual, diff_dir );
    }

    std::cout << "All tests PASSED." << std::endl;
    return 0;
}
